export interface RateLimiterOptions {
  /** API key generated by the Token Bucket Rate Limiter service. */
  apiKey: string;
}

export interface PolicyConfig {
  name: string;
  capacity: number;
  refillRate: number;
  /** Refill interval in seconds. */
  interval: number;
}

export interface RateLimitCheckData {
  allowed: true;
  limit: number;
  remainingTokens: number;
  retryAfter: number;
}

export interface RateLimitAllowedResult extends RateLimitCheckData {
  allowed: true;
}

export interface RateLimitBlockedResult {
  allowed: false;
  retryAfter?: number;
}

export type RateLimitResult = RateLimitAllowedResult | RateLimitBlockedResult;

export interface SyncPoliciesResult {
  synced: number;
}

export interface ApiResponse<T> {
  success: boolean;
  message?: string;
  data?: T;
}
